[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = ".netlify/.next/cache/**"
  SECRETS_SCAN_OMIT_KEYS = "CONTACT_TO_EMAIL,NEXT_PUBLIC_CONTACT_EMAIL"

[[plugins]]
  package = "@netlify/plugin-nextjs"